### ISSUE TITLE
HTML is recognised as Laravel Blade

### ISSUE THREAD

**Issue by excellent6** [onecentlin/laravel-blade-snippets-vscode#1]
The markup of the language is wrong. If I create an empty HTML file, it is detected as Blade. 

!['HTML file'](https://s11.postimg.io/5t0urqcer/image.png)

**Comment by onecentlin** [comment]
In order to enable `emmet` in blade template, it's the current solution to make it work.
I'll keep finding a better way to detect blade template without overriding HTML detection.

**Comment by onecentlin** [comment]
Good news! Microsoft vscode team keeps trying to support emmet for other file extensions instead of private hard coding. Hopefully it will support in next release version!

> Feature Request: Enable emmet for other file extensions. (https://github.com/Microsoft/vscode/issues/9500)

**Comment by mrmlnc** [comment]
@onecentlin, yes, now we support all languages. You need to change the language identifier :panda_face:
