### ISSUE TITLE
Feature: Blade Template Formatting

### ISSUE THREAD

**Issue by mtpultz** [onecentlin/laravel-blade-snippets-vscode#10]
Great plugin I found it really useful, but I do notice that formatting on save or any other type of formatting of the HTML markup doesn't occur as it does in a normal `.html` file.  

Is it possible to have the formatting work in blade templates?

**Comment by onecentlin** [comment]
@mtpultz Thanks for the feedback. I do work on this. However, I still haven't found the best solution so far.

**Comment by nivv** [comment]
The only thing missing really. I keep going back to Atom to fix really messy files

**Comment by TheColorRed** [comment]
I think I may have a solution for this

**Comment by TheColorRed** [comment]
Okay I found the solution and it works. However, it messes up some of the formatting of the laravel tags sometimes.

**Comment by nivv** [comment]
@TheColorRed Any progress? :)

**Comment by nicooprat** [comment]
Isn't it the purpose of this config?

```
"files.associations": {
    "*.blade.php": "html"
},
```

**Comment by TheColorRed** [comment]
@nivv no I haven't looked at it in a while...

**Comment by willsilvano** [comment]
I need this a lot! :(

**Comment by nicooprat** [comment]
Same, literally made me switch back to Sublime Text!

**Comment by Jakobud** [comment]
Formats blade tags in a weird way. Really inconvenient that you can't disable it.

**Comment by Sarav-S** [comment]
@Jakobud I too have same issue. Its formatting everything in single line. @onecentlin is there a way to disable formatting?

**Comment by onecentlin** [comment]
@Sarav-S, @Jakobud  I'm working on this issue as well. Sorry for the inconvenience.

**Comment by TheColorRed** [comment]
I have found a snippet that is supposed to format the blade nicely. I am however not getting it to work :(

The snippet uses [htmlparser2](https://github.com/fb55/htmlparser2), so maybe if I write my own way to work with htmlparser2, it will work better than the snippet I found.

**Comment by shaneparsons** [comment]
Let me know if this belongs in its own issue, but the **Format Selection** command doesn't seem to work with the newly implemented formatting.
