### ISSUE TITLE
the formatter breaks long lines

### ISSUE THREAD

**Issue by mobayen** [onecentlin/laravel-blade-snippets-vscode#102]
Hello 
the blade formatter breaks long lines and split it into two or more lines!
sometimes it causes issues
also, I prefer the VScode default word-wrap, if I need the functionality

is there a way to disable it?

thanks for all the work done for this extension!

**Comment by onecentlin** [comment]
@mobayen you may add `"blade.format.enable": false,` to your VSCode setting
