### ISSUE TITLE
Blade highlight not working

### ISSUE THREAD

**Issue by mgarcia96** [onecentlin/laravel-blade-snippets-vscode#103]
Look at this:
![image](https://user-images.githubusercontent.com/6561770/67273271-67908980-f4be-11e9-9d9b-5ba774111e13.png)

![image](https://user-images.githubusercontent.com/6561770/67273278-6bbca700-f4be-11e9-89d7-851e6e320493.png)

**Comment by FadyBengoufa** [comment]
I'm having the same problem :(
