### ISSUE TITLE
Adding {{} (double curly braces + 1 closing curly braces) unindents that line

### ISSUE THREAD

**Issue by rafaeldotjs** [onecentlin/laravel-blade-snippets-vscode#105]
When I add double curly braces + 1 closing curly brace the snippet unindents that line by 1 level.

For example, before adding double curly braces:
![before](https://user-images.githubusercontent.com/2362309/69426509-2fbe7100-0d0c-11ea-98ff-50abcfca5855.JPG)

And after adding {{}:
![after](https://user-images.githubusercontent.com/2362309/69426523-377e1580-0d0c-11ea-871b-10cffca36421.JPG)

**Comment by bojandurmic** [comment]
Anyone can fix this?

**Comment by crumb1e** [comment]
The fix in #58 seems to sort this out for me!

**Comment by onecentlin** [comment]
I add this solution to wiki page:
https://github.com/onecentlin/laravel-blade-snippets-vscode/wiki
