### ISSUE TITLE
请问这个图的打出 html:5 自动填写<!doctype...等内容是怎么出来的？

### ISSUE THREAD

**Issue by cloverzrg** [onecentlin/laravel-blade-snippets-vscode#11]
我打出html:5没有反应
https://github.com/onecentlin/laravel-blade-snippets-vscode/raw/master/images/screenshot.gif

**Comment by onecentlin** [comment]
@cloverzrg This is emmet snippets by default. To enable emmet in Laravel Blade, you must add the following settings.

```json
    "emmet.syntaxProfiles": {
        "blade": "html"
    },
```

Also, please make sure your file is saved as `*.blade.php` or switched to language mode `Laravel Blade`.
