### ISSUE TITLE
Blade syntax highlight not working

### ISSUE THREAD

**Issue by olivierr91** [onecentlin/laravel-blade-snippets-vscode#112]
I installed the blade extension, and even though the file is detected as "Laravel Blade", syntax highlight does not seem to work.

I should get something like this:

![image](https://user-images.githubusercontent.com/6403705/78146947-d6282a80-7400-11ea-95a8-2dbe11d39ef5.png)

Instead I am getting something like this:

![image](https://user-images.githubusercontent.com/6403705/78146996-e5a77380-7400-11ea-832b-6cf7f4072b9b.png)

VS Code 1.43.2 on Windows 10 1909 x64

**Comment by YannickYayo** [comment]
Same issue here on Linux Mint

**Comment by onecentlin** [comment]
Try to switch between different color theme. It may show differently.

**Comment by dgloriaweb** [comment]
Hi, same here, no blade syntax highlighting with any extensions. I use Monokai but tried to switch. No luck. Windows, VS Code.

**Comment by cpof-tea** [comment]
It seems, it is not supported for now.

Tried to test some adjustments to extension at the fork
![image](https://user-images.githubusercontent.com/29537473/137566929-01e1830d-4abd-490b-918b-5638378eb5e4.png)

Looks pretty well, but I could use some suggestions for tests
