### ISSUE TITLE
Emmet not working.

### ISSUE THREAD

**Issue by HackerFinn** [onecentlin/laravel-blade-snippets-vscode#12]
Emmet does not work in blade using the "Laravel Blade Snippets" extension, even after adding the following configuration:
```json
    "emmet.syntaxProfiles": {
        "blade": "html"
    },
```
- VSCode Version: 1.13.1
- OS Version: Win 10.

**Comment by onecentlin** [comment]
@HackerFinn Please make sure your file is saved as `*.blade.php` or switched language mode to `Laravel Blade`.

**Comment by HackerFinn** [comment]
I did.
Now that I think about it, it may be caused by this bug in VS Code: https://github.com/Microsoft/vscode/issues/28837#issuecomment-310749409
