### ISSUE TITLE
Blade files like filename.blade.php are not highlighted in explorer as php files after installing extention. 

### ISSUE THREAD

**Issue by IvankvKharkiv** [onecentlin/laravel-blade-snippets-vscode#122]
Blade files like filename.blade.php are not highlighted in explorer as php files after installing extension. They don't have the php file standard Icons. How can I use all the other features of extension and still see my .blade.php files in explorer as php files with php icon?

**Comment by onecentlin** [comment]
@IvankvKharkiv You may search `vscode-icons` or `Material Icon Theme` extensions in vscode marketplace

**Comment by IvankvKharkiv** [comment]
Thank you for your answer, I have installed "seti-icons" which looks pretty much the same as original seti-icons of vscode, as long as I really like this theme of icons.
But still it would be better if nothing is changed when installing "laravel-blade-snippets-vscode".
Regards.
