### ISSUE TITLE
Laravel @props is not being formatted correctly

### ISSUE THREAD

**Issue by MohammadxAli** [onecentlin/laravel-blade-snippets-vscode#126]
Hi, thanks for your awesome extension.
There's an issue that I ran into when trying to format a blade file that has `@props` in it.
Here's an example of file:
```
@props([
    'variant'   => 'primary',
    'colors'    => [
        'primary'   => 'btn-primary',
        'secondary' => 'btn-secondary',
        'danger' => 'btn-danger',
    ]
])

<button {{$attributes->merge(['class' => "btn {$colors[$variant]}"])}}>
    <span>{{ $slot }}</span>
</button>

```
After formatting it turns into this:
```
@props([
'variant' => 'primary',
'colors' => [
'primary' => 'btn-primary',
'secondary' => 'btn-secondary',
'danger' => 'btn-danger',
]
])
<button {{$attributes->merge(['class' => "btn {$colors[$variant]}"])}}>
    <span>{{ $slot }}</span>
</button>
```

And here's a screencast:

https://user-images.githubusercontent.com/67554982/109468721-406aa480-7a82-11eb-8b85-6e0a9cd89687.mp4

**Comment by onecentlin** [comment]
@MohammadxAli For advanced formatting, you may consider install `Laravel Blade formatter` extension (https://marketplace.visualstudio.com/items?itemName=shufo.vscode-blade-formatter)

**Comment by MohammadxAli** [comment]
Yeah I eventually started using that one 👍
