### ISSUE TITLE
@php @endphp syntax highlight

### ISSUE THREAD

**Issue by gracefullight** [onecentlin/laravel-blade-snippets-vscode#13]
![image](https://user-images.githubusercontent.com/11773683/27425778-8c4c9758-5774-11e7-848d-9cc729497ece.png)

Is syntax highlighting between @php and @endphp possible?

**Comment by onecentlin** [comment]
@brendaniel I did try to enable syntax highlighting in this block. However, I haven't found a good solution to solve this yet.

**Comment by CristianH033** [comment]
Me too, somebody know if is possible?

**Comment by RCady** [comment]
Well, I really wish I understood how this all works. I'll try and dive into it. But it seems to me "tricking" it into thinking `@php` is equal to `<?php` would be the answer to the problem.

**Comment by onecentlin** [comment]
Syntax highlight fixed in v1.14.x
