### ISSUE TITLE
How to disable snippets in VSCode? I just want the formatting of this extension

### ISSUE THREAD

**Issue by JoaoHamerski** [onecentlin/laravel-blade-snippets-vscode#131]
I just want the syntax highlight and formatting features, there is some way to do that?

The issue with snippets are that it's annoying me a lot, even to write some html elements the snippets popup shows and i missly trigger it.

**Comment by jonjieviduya** [comment]
Any update with this?

**Comment by lakuapik** [comment]
You could disable it with custom user configuration like this:

```json
"[blade]": {
    "editor.snippetSuggestions": "none"
}
```

It will disable snippet suggestion when vscode detects you are editing blade file.
