### ISSUE TITLE
Highlighting open and closing html tags

### ISSUE THREAD

**Issue by kinnedev** [onecentlin/laravel-blade-snippets-vscode#14]
I may be missing a feature, but my HTML highlighting seems to be gone. 

Is there a way to see open and closing brackets on a tag similar to how the .html files work?

**Comment by onecentlin** [comment]
@kinnedev Indeed, not only you, but also lots of VSCode PHP developers encounter this issue ([vscode#2915](https://github.com/Microsoft/vscode/issues/2915)).

**Comment by kinnedev** [comment]
@onecentlin I see! So this seems to be a known issue for the IDE itself?

**Comment by kinnedev** [comment]
Found a package that does that trick! Gonna close this now.

**Comment by Dalot** [comment]
@kinnedev You've found a package that solves the issue, would you bother to share?
