### ISSUE TITLE
Syntax Highlighting for Laravel 9 Slot Name Shortcut

### ISSUE THREAD

**Issue by thecodeclimber** [onecentlin/laravel-blade-snippets-vscode#148]
In Laravel 9 there is a new shorthand for named slots:  https://laravel.com/docs/9.x/releases#slot-name-shortcut

However, there does not seem to be any syntax highlighting for this new feature -- as this screenshot indicates:

![image](https://user-images.githubusercontent.com/65869221/154588583-a4d2207e-0e16-4d5a-90a2-ee6bf6bb9fde.png)

`<x-modal.trigger>` relates to a blade component within the `modal` component directory whereas  `<x-slot:trigger>` relates to a named slot within the `<x-modal>` component.

It would be nice if we could have syntax highlighting for `<x-slot:trigger>` similar to what we have for `<x-modal.trigger>`.  Even better would be to have a different color for `:trigger` then we have for `x-slot` to easily see which slot we are accessing.

**Comment by zpoll92** [comment]
I have the same issue. Also, the formatting of texts is not functioning correctly inside those tags.

**Comment by sclause2412** [comment]
According to https://laravel.com/docs/10.x/blade#slots the named slot closing tag can be simplified to `</x-slot>`. I tested it and both variants work with Laravel:
```
<x-slot:trigger>Open Modal</x-slot:trigger>
<x-slot:trigger>Open Modal</x-slot>
```
Therefore, both variants should be supported.

For the moment I will use the long version as the indentation is done correctly, while using the short version destroys the layout.
