### ISSUE TITLE
No syntax highlighting for component from a package

### ISSUE THREAD

**Issue by robinheidrich** [onecentlin/laravel-blade-snippets-vscode#149]
There is no syntax highlighting for components from a package.  It is only displayed in red.

![Screenshot_1](https://user-images.githubusercontent.com/23118399/155611224-4a2c7434-cfc3-4657-8579-26e65f50ede6.png)

**Comment by nicolaibaaring** [comment]
This is not only the case for components from packages. It also happens for custom component namespaces in your own code.

Has anyone looked into this issue?

**Comment by onecentlin** [comment]
@robinheidrich @nicolaibaaring 
This is enhanced in PR #175
Please update extension to v1.35
