### ISSUE TITLE
indent not working in blade file

### ISSUE THREAD

**Issue by izcream** [onecentlin/laravel-blade-snippets-vscode#15]
when i change syntax to html it's work correctly but when i change back to laravel blade indent not working. i add emmet syntaxprofile already.

how to solve this issue?

THX

**Comment by izcream** [comment]
This problem still not resolve in new VScode Version

![untitled](https://user-images.githubusercontent.com/10282500/29348247-62229ddc-827c-11e7-964e-ea8202d6028f.gif)

**Comment by izcream** [comment]
@onecentlin how i  solve this problem?

ps. sorry for mention you

**Comment by onecentlin** [comment]
@izcream Indeed, VS Code currently does not support indent for other then HTML. I am working on formatting blade template; however, it's not quite work well on some blade blocks.
(The screenshot works because it was initially set to language `HTML`)

**Comment by izcream** [comment]
ok long time vscode not fixed - -
