### ISSUE TITLE
space after double quotes

### ISSUE THREAD

**Issue by mohmmedAliDesouky** [onecentlin/laravel-blade-snippets-vscode#154]
how i can disable this
before formating
` <?php if (isset($title) && $title == "Settings") { echo "Active" ; } ?>`
after
` <?php if (isset($title) && $title == " Settings") { echo "Active" ; } ?>`

**Comment by mohmmedAliDesouky** [comment]
.

**Comment by rizqul** [comment]
i have same problem and need the solution too :(

**Comment by granvilla** [comment]
up!

**Comment by muhammedkaraoglu** [comment]
Up !

**Comment by onecentlin** [comment]
@mohmmedAliDesouky Is there any extension conflict with it? Or which formatter are you using?
I couldn't reproduce this issue.

**Comment by zildjianvitoo** [comment]
same issue

**Comment by mask477** [comment]
did anyone find a solution to this?

**Comment by MiladRad** [comment]
up
