### ISSUE TITLE
Tag Matching

### ISSUE THREAD

**Issue by TheColorRed** [onecentlin/laravel-blade-snippets-vscode#16]
It would be nice if tag matching worked, because every time I need to match a opening `div` with a closing `div` I need to switch to html mode.

Currently if you put the cursor over a `div` tag it selects all of the `div`'s

If I am not mistaken this could be included to support this https://github.com/Microsoft/vscode-html-languageservice

**Comment by TheColorRed** [comment]
I forked the project and added the code, I have it working!

**Comment by nicooprat** [comment]
I got all Emmet features working fine again in Blade files by adding this config:

```
"files.associations": {
    "*.blade.php": "html"
},
"emmet.includeLanguages": {
    "blade": "html"
},
```

Also I found this extension really handy when having to rename some HTML tags: https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
