### ISSUE TITLE
Enable Emmet for Blade VS Code 1.5+

### ISSUE THREAD

**Issue by adevade** [onecentlin/laravel-blade-snippets-vscode#18]
When I copied the given code to my User Settings it didn't work. 
```json
"emmet.syntaxProfiles": {
    "blade": "html"
},
```

However, the code below seems to activate Emmet for Blade again. 

```json
"emmet.includeLanguages": {
    "blade": "html"
},
```

Thanks for a great extension!

**Comment by Pancrisp** [comment]
Emmet 2.0 (newEmmet) is enabled by default as of version 1.15

Basically, 
> **emmet.includeLanguages** will be used in the new emmet model to map languages unsupported by emmet to one of the languages that is supported by emmet.

> **emmet.sytnaxProfiles** will continue to be used for the same purpose, but only in the old emmet model

[New emmet config](https://github.com/Microsoft/vscode/issues/29678#issuecomment-311806214)

So things should continue to work as before as long as users update their emmet configuration to reflect these new changes.

**Comment by omulmicsinegru** [comment]
Hello, 

In my settings file i replaced 
"emmet.syntaxProfiles": {
    "blade": "html"
},

With: 
"emmet.includeLanguages": {
    "blade": "html"
},

It still did not work. 
@adevade did you have to do anything else to make it work?

**Comment by izcream** [comment]
You has problem with indent when use?
<img width="183" alt="screen shot 2017-08-16 at 11 43 57" src="https://user-images.githubusercontent.com/10282500/29347644-3c4dbd98-8278-11e7-9dad-c48d414b1ef7.png">

i got this problem it's not indent like example gif in readme
how do i solve it?

**Comment by Bigdragon13th** [comment]
@omulmicsinegru I'm facing the same problem. Already tried both settings with no luck, did you get  it to work yet?

**Comment by Bigdragon13th** [comment]
Nevermind, I got it to work now with `emmet.includeLanguages`

The reason why mine is not working is because I having this setting. Remove it make the plugin work again.

```json
"[blade]": {
	"editor.quickSuggestions": {
		"other": false,
		"comments": false,
		"strings": false
	}
},
```

**Comment by omulmicsinegru** [comment]
@Bigdragon13th No , i did not get it to work.

Thank you for the tip, i'll give it a shot myself.

**Comment by nicooprat** [comment]
This fixed it for me:

```
"files.associations": {
    "*.blade.php": "html"
},
"emmet.includeLanguages": {
    "blade": "html"
},
```

**Comment by fansheng0594** [comment]
> You has problem with indent when use? <img alt="screen shot 2017-08-16 at 11 43 57" width="183" src="https://user-images.githubusercontent.com/10282500/29347644-3c4dbd98-8278-11e7-9dad-c48d414b1ef7.png">
> 
> i got this problem it's not indent like example gif in readme how do i solve it?

before:
```html
<div>
</div>
```html

Install `laravel blade snippets` extension:
```html
<div>
        |     {{-- cursor positon --}}
</div>
```html
