### ISSUE TITLE
Suggestion: Make Blade directive and `@` same color as functions in theme.

### ISSUE THREAD

**Issue by mikebronner** [onecentlin/laravel-blade-snippets-vscode#22]
Right now the blade directives appear in the same color as HTML tags. It would be good to visually differentiate blade directives from tags, my suggestion would be to make them the same color that functions are defined as in the syntax theme.

My guess is that the blade grammar is setting blade directives as tags, instead of functions?

Any suggestions? (I haven't figured out how to manually override the setting in user settings, if that is even at all possible.)

**Comment by onecentlin** [comment]
@mikebronner Thank you for the suggestions. Merged PR #23.
