### ISSUE TITLE
Tag attributes completition

### ISSUE THREAD

**Issue by yamenarahman** [onecentlin/laravel-blade-snippets-vscode#24]
This is in html file:
![html](https://user-images.githubusercontent.com/24607365/30340631-6248b5da-97f3-11e7-918b-7c23ba02225a.gif)
While in blade:
![blade](https://user-images.githubusercontent.com/24607365/30340654-75b40c28-97f3-11e7-9734-0bdd915dca5c.gif)
Notice the indent and the tag attributes feature. The snippets are working and my user settings are 
```
"emmet.triggerExpansionOnTab": true,
    "emmet.includeLanguages": {
        "blade": "html",
    },
```
as recommended.

**Comment by onecentlin** [comment]
Issue updated in v1.16.0
