### ISSUE TITLE
Echo and comment add more slash

### ISSUE THREAD

**Issue by hairulardi** [onecentlin/laravel-blade-snippets-vscode#3]
![bladesnippet](https://cloud.githubusercontent.com/assets/22541934/22105992/3b3ec6c0-de79-11e6-9c3c-8ab98e56fe39.gif)

Visual Studio Code : 1.8.1
Laravel Blade Snippets : 1.5.1

**Comment by onecentlin** [comment]
@hairulardi  thanks for your feedback. I'll fix it ASAP.

**Comment by tradzero** [comment]
and i think like `lv:csrf-token` , and 'lv:*' have same problem

**Comment by onecentlin** [comment]
@tradzero Indeed. I'll fix these as well.
