### ISSUE TITLE
How do I change or disable this extensions auto-formatting?

### ISSUE THREAD

**Issue by Jakobud** [onecentlin/laravel-blade-snippets-vscode#30]
Your extension auto formats my blade documents. I have the following block of code:

```
<input id="username" name="username" type="text" value="{{ old('username') }}">
@if ($errors->has('username'))
<div class="error">Username Error here</div>
@endif
```

And when I save the document or run "Format Document" it formats it to this:

```
<input id="username" name="username" type="text" value="{{ old('username') }}"> @if ($errors->has('username'))
<div class="error">Username Error here</div>
@endif
```

Really, really annoying. It is definitely this extension doing it to because if I disable all extensions it does not format the document. But if I then enable ONLY this extension, it formats the document.

How do I turn off this feature? Or how do I control the formatting rules? When I search in my settings for "laravel" I see zero settings to control this extension's features and behavior.

Also, kind of weird that It doesn't say anything about formatting on the extension page. If the extension is a "snippet" extension as the title implies maybe you should not add in hidden features like formatting that cannot be disabled.

**Comment by memborsky** [comment]
After the 1.10 release, it appears that if you had the following setting in your user/workspace settings, it will incorrectly format the document:

```json
"files.associations": {
    "*.blade.php": "html"
}
```



My html format settings

```json
    "html.format.endWithNewline": true,
    "html.format.indentHandlebars": true,
    "html.format.indentInnerHtml": true,
    "html.format.wrapLineLength": 0,
```

**Comment by timothyallan** [comment]
I just started having this happen too. All the indents of my @ blocks are wrecked, and it now places multiple @ blocks in a single line

i.e. something that used to be nicely indented/formatted over multiple lines, now turns into this:

```
@extends('xyz') @section('abc') @include('lmno') @if (xyz= def)
<script src="xyz"></script>
@else
<script src="abc"></script>
@endif @endsection 
```

**Comment by Jakobud** [comment]
@memborsky Unfortunately I do not have 
```
"files.associations": {
    "*.blade.php": "html"
}
```
and I still get the formatting issue. Uninstalling this extension until this fixed is the only way for it to work I guess.

**Comment by memborsky** [comment]
@Jakobud You might be able to temporarily stop it by opening up `.vscode\extensions\onecentlin.laravel-blade-1.10.0\out\src\extension.js` in your user directory and comment out line #31:

```javascript
  context.subscriptions.push(vscode.languages.registerDocumentFormattingEditProvider(documentSelector, new DocumentFormat))
```

**Comment by oldskool73** [comment]
The reformat is also ignoring the settings I have in `.editorconfig` and changing everything to tabs when I've configured them to be spaces. Unfortunately this is a disabled extension until this is fixed/removed. 

Just gonna say also, this is extension is called 'laravel blade snippets', it should just stick to doing that, it shouldn't be doing any formatting at all. If I wanted a 'laravel blade formatter' I'd install a different extension, or just use one of the other formatter plugins I already have installed.

**Comment by godbout** [comment]
Took me about 2 hours to find why my spaces where replaced with tabs. Same thing as here, tried many settings but it doesn't work. Unfortunately, I have to disable the extension.

**Comment by onecentlin** [comment]
Update extension to v1.12.0.
To disable blade format, please add `"blade.format.enable": false` to User Setting.

**Comment by yabasha** [comment]
I'm still facing this issue with V.1.13.0, it's very annoying :(
