### ISSUE TITLE
html elements not indenting With the latest vscode

### ISSUE THREAD

**Issue by AnthonyMichaelc** [onecentlin/laravel-blade-snippets-vscode#31]
In regular html pages if I type (below) and click enter while the cursor is in the middle of the tags 

`<p></p>`

It will look like this:
```
<p>
   (indented content)
</p>
```

With the latest vscode and all extensions, it seems this extension is not executing the indent and leaving me with this when doing the same in a page.blade.php file: 
<p>
</p>

**Comment by AnthonyMichaelc** [comment]
Is there a new setting missing from my user settings that is doing this because as much as I like using vscode this is making me resort to other editors for laravel because it adds extra steps and time that can be utilized focused on what my code is doing. It literally drops it down to the next line, unlike the showcased screencast in the extensions market

**Comment by nivv** [comment]
I've added this to my config:

```json
    "files.associations": {
        "*.blade.php": "html"
    },
    "emmet.syntaxProfiles": {
        "vue-html": "html",
        "vue": "html",
        "blade": "html"
    },
    "emmet.includeLanguages": {
        "vue-html": "html",
        "vue": "html",
        "blade": "html"
    },
```
However, this will scramble most of the blade tags

**Comment by AnthonyMichaelc** [comment]
@nivv I implement that line and was prompted with your installations has been corrupted, then it constantly changed the syntax at the bottom to html rather than blade.

**Comment by nivv** [comment]
@AnthonyMichaelc try to remove this option:

```json
    "files.associations": {
        "*.blade.php": "html"
    },
```

**Comment by AnthonyMichaelc** [comment]
@nivv Adding all the config you listed turns it into an html syntax and does the indent but it then removes all blade syntax (making having the extension useless). Removing just the:

```
"files.associations": {
        "*.blade.php": "html"
    },
```

returns the syntax to laravel blade but does not do the indent

**Comment by AnthonyMichaelc** [comment]
Is there any update on this issue? I am still not able to use blade files like I was able to before.

**Comment by AnthonyMichaelc** [comment]
I assume this issue is not going to get resolved and will likely force people using vscode for laravel to switch back to another editor....
