### ISSUE TITLE
ON saving a .blade file it inlines all blade syntax

### ISSUE THREAD

**Issue by simondavies** [onecentlin/laravel-blade-snippets-vscode#32]
OK when I write a blank blade set up as below 

        @extends('layouts.main') 
        @section('content')

        @stop

Then on saving it inlines the code as follows.

`@extends('layouts.main') @section('content') @stop`

And when putting html code within the content section it still only inlines the top part eg below:

      @extends('layouts.main') @section('content')
         <div>

         </div>
       @stop`

Is there a setting or config needs sorting or is this a conflict etc

**Comment by zackkrida** [comment]
Seeing this as well. I believe it's related to https://github.com/onecentlin/laravel-blade-snippets-vscode/pull/17

**Comment by yamenarahman** [comment]
These two settings are responsible for that
```
  "editor.formatOnSave": true,
    "files.associations": {
        ".blade": "html"
    },
```
So I suggest to disable one of them untill this package updates its own format provider.

**Comment by vpicone** [comment]
Until this is fixed, you can disable format on save for blade files by adding this to your settings:

```json
"[blade]": {
    "editor.formatOnSave": false,
  },
```
That we'll you'll keep the syntax highlighting and snippets while forgoing the formatting.
