### ISSUE TITLE
Turn off syntax highlighting but keep snippets

### ISSUE THREAD

**Issue by jaydickinson** [onecentlin/laravel-blade-snippets-vscode#33]
Is it possible to turn off the syntax highlighting and keep the snippets? 

I use another Extension that works better for blade highlighting but this extension just overwrites the syntax highlighting if it's installed so I can't use the snippets which are great.

Thanks

**Comment by godbout** [comment]
@jaydickinson It's possible now with a setting: ```"blade.format.enable": true```

**Comment by onecentlin** [comment]
Syntax highlighting is bundled in extension. Therefore, you cannot just turn off syntax highlighting but keep snippets. Since release version 1.14.2, better syntax highlighting and other features are supported, you may try it out! =)
