### ISSUE TITLE
Wrong comment with CTRL + / at in page js

### ISSUE THREAD

**Issue by heroahmadi** [onecentlin/laravel-blade-snippets-vscode#34]
Commenting with CTRL + / keeps adding html comment `{{-- --}}` instead of javascript comment `//` 
And also after creating div tag and press enter, the cursor didn't automatically adjust to create newline between opening and closing tag. I mean it should be:
```
<div>
         |
</div>
```
not
```
<div>
|</div>
```

please fix this soon, thanks!

**Comment by onecentlin** [comment]
Comment issue updated in v1.16.0
