### ISSUE TITLE
Problem for auto indent

### ISSUE THREAD

**Issue by bulfaitelo** [onecentlin/laravel-blade-snippets-vscode#35]
When I create a new class for example `".abc"` I use the tab it creates the div `<div class="abc"></div>` correctly, but when I press the Enter it does not ident correctly.

example:
![image](https://user-images.githubusercontent.com/4989569/33232552-7504f252-d1ef-11e7-8da7-e305eb98fe3b.png)

i need:
![image](https://user-images.githubusercontent.com/4989569/33232562-8a9e638c-d1ef-11e7-86fe-4bed109a9ede.png)

Can someone help me?

My actual user settings
![image](https://user-images.githubusercontent.com/4989569/33232577-bc60b488-d1ef-11e7-95f6-fe0470f21008.png)

**Comment by AnthonyMichaelc** [comment]
Have the same issue and also thought it could be vscode's issue but they outline the issue that all the blade extensions are currently having
[ https://github.com/Microsoft/vscode/issues/39142#issuecomment-349502568 ]

**Comment by AnthonyMichaelc** [comment]
this was never address... your extension is useless without fixing this issue..

**Comment by onecentlin** [comment]
Please remove `emmet.syntaxProfiles` setting. This is for VS Code v.1.14 or below.

**Comment by AnthonyMichaelc** [comment]
I don't currently have that. I linked the current setting within that issue link i sent to vscode where they explained that you and all the other laravel blade extensions are not handling the html as html which is why vscode cannot communicate with the extensions to complete the syntax and allow blade syntaxing. this is the only emmet settings I have as I was advised by the vscode team it is needed with the latest builds

```
"emmet.includeLanguages": {
    "vue-html": "html",
    "vue": "html",
    "blade": "html",
    "edge": "html",
    "php": "html"
  },
```

**Comment by onecentlin** [comment]
@AnthonyMichaelc I tested the extension in a newly installed VS Code environment.

- VS Code v1.19.1
- Laravel Blade Snippets v1.11.0

With settings below:
```json
{
    "emmet.includeLanguages": {
        "blade": "html"
    },
    "emmet.triggerExpansionOnTab": true
}
```

It did work well with HTML auto indent.
Please make sure the file mode is `Laravel Blade`
