### ISSUE TITLE
javascript autocompletion not working in script tag

### ISSUE THREAD

**Issue by adrianriyadi** [onecentlin/laravel-blade-snippets-vscode#39]
I hope this issue will be fix soon.. Blade file doesn't work like HTML file that has javascript autocompletion inside script tag. If I change blade to HTML file, javascript autocompletion will work but then syntax highlight from Laravel Snippet will stop to work.

**Comment by tiansin** [comment]
#42 
Hope as you wish.

**Comment by adrianriyadi** [comment]
yeah. exactly, that's what I want. thanks a lot @tiansin :)
