### ISSUE TITLE
Use space on format document

### ISSUE THREAD

**Issue by alainbelez** [onecentlin/laravel-blade-snippets-vscode#40]
How do you use space when formatting the document? it always use tab, even if the settings below is set to space

**Comment by godbout** [comment]
Same issue. For the moment, if you want to keep the snippets and highlighting, the best way is to disable blade formatting. See https://github.com/onecentlin/laravel-blade-snippets-vscode/issues/30.

**Comment by onecentlin** [comment]
@godbout I'm working on this, and should be able to release it soon.

**Comment by godbout** [comment]
Great, thanks!
