### ISSUE TITLE
Double emmet suggestions in the latest update

### ISSUE THREAD

**Issue by ramya-rao-a** [onecentlin/laravel-blade-snippets-vscode#48]
The Readme has the below instruction

<img width="794" alt="screen shot 2018-02-17 at 5 20 20 pm" src="https://user-images.githubusercontent.com/16890566/36347230-de0bf7ce-1406-11e8-9680-48e398c03bc9.png">

The above is needed for languages that do not have in built emmet support

The latest update to this extension uses a fork of the html language server which supports emmet. So now, users who follow the above instruction will get double emmet suggestions

<img width="789" alt="screen shot 2018-02-17 at 5 21 32 pm" src="https://user-images.githubusercontent.com/16890566/36347240-062316ac-1407-11e8-8cbe-46589490a806.png">

**Comment by tiansin** [comment]
@ramya-rao-a
Thank you for the details of the extension observation, which I did not consider.
You need to change the description of the extension emmet. @onecentlin
