### ISSUE TITLE
<?php ?> and @php @endphp tags not handled properly

### ISSUE THREAD

**Issue by vesper8** [onecentlin/laravel-blade-snippets-vscode#49]
If I use <?php ?> then the php inside just gets ignored when I format the document

Using cmd-/ to comment inside the <?php ?> tags however applies the wrong comment syntax

If I use @php @endphp, the wrong comment syntax are also applied, and if I use the format document it removes all lines breaks and puts everything on one line basically

**Comment by onecentlin** [comment]
Comment issue updated in v1.16.0

**Comment by robinparisi** [comment]
Same here

**Comment by onecentlin** [comment]
@robinparisi Do you switch language mode to `Laravel Blade`? I believed this issue was fixed in v1.16.0, please try again.
