### ISSUE TITLE
@php() with html tag syntax highlight

### ISSUE THREAD

**Issue by DoopSky** [onecentlin/laravel-blade-snippets-vscode#53]
![_20180224201351](https://user-images.githubusercontent.com/8330408/36630302-43e4f81e-199f-11e8-834f-dfb527c25e5a.png)
Enable the plugin.

![3](https://user-images.githubusercontent.com/8330408/36630369-4df655d6-19a0-11e8-9bfd-4329196f9468.png)
Disable the plugin.

@onecentlin Thank you very muck for your plugin. It's very helpful.

I use [Roots/Sage](https://github.com/roots/sage) WordPress Template.

The Html tag has different color.

How to fix it? Thank you.

**Comment by cyptus** [comment]
with the use of the shorthand @php(<CODE>) instead of @php <CODE> @endphp i also lose syntax highlighting, this is in combination with roots/sage very annoying :-/

**Comment by naknak987** [comment]
@onecentlin   
This is still an issue with the longhand format.  
`@php <CODE> @endphp`  
I'm not using Roots/Sage.
