### ISSUE TITLE
Single quotes creates the colour formatting

### ISSUE THREAD

**Issue by jpmurray** [onecentlin/laravel-blade-snippets-vscode#56]
Adding a single quote changes the color formatting as if it's waiting for it to close... For example:

![screen shot 2018-03-06 at 1 52 32 pm](https://user-images.githubusercontent.com/1550428/37051894-b7466664-2145-11e8-92c6-a7cf833e00dc.png)

**Comment by onecentlin** [comment]
@jpmurray This should be fixed, please try again.

**Comment by hakanersu** [comment]
I did have same problem but it seems i had another laravel syntax highlighter and it cause my problem.

**Comment by cpof-tea** [comment]
@onecentlin There's no problems at this since last reply.

![image](https://user-images.githubusercontent.com/29537473/145881863-5966658d-18b2-4667-88bb-7adee197682e.png)

Issue can be closed
