### ISSUE TITLE
Closing curly brace breaks indentation

### ISSUE THREAD

**Issue by joaomnb** [onecentlin/laravel-blade-snippets-vscode#58]
When writing a Blade Echo tag with double curly braces inside an HTML attribute, auto-close doesn't work and indentation breaks:

![untitled](https://user-images.githubusercontent.com/1238088/37483548-1cc19fe2-287e-11e8-9d8f-abe78eaf9dee.gif)

Outside the HTML tag, it works as expected.

**Comment by elbojoloco** [comment]
I'm experiencing the same issue. Please fix.

**Comment by amadeann** [comment]
Can confirm this. Each time I open two curly braces when I close it, the indentation of that line goes by 1 tab to the left.

**Comment by elbojoloco** [comment]
Yes I tried disabling the extension and then close a curly brace as shown above, the same happens. Not an issue with this package but with VSCode, please close :)

**Comment by amarhafizuddeen** [comment]
Hello. I have similarly experienced the same problems. After browsing around for some time, I have managed to fix this issue by changing the settings for 'Auto Closing Brackets' to 'always'. You can find this in the vscode settings. Hope this help!

**Comment by paulpretorius** [comment]
> Hello. I have similarly experienced the same problems. After browsing around for some time, I have managed to fix this issue by changing the settings for 'Auto Closing Brackets' to 'always'. You can find this in the vscode settings. Hope this help!

@amarhafizuddeen , thank you, this helped.

I managed to fix the problem for blades specifically, by keeping the global `Auto Closing Brackets` setting as `languageDefined`, but adding the following to my `settings.json` file:

```
"[blade]": {
    "editor.autoClosingBrackets": "always"
}
```
