### ISSUE TITLE
HTML autocomplete doesn't work

### ISSUE THREAD

**Issue by qcol** [onecentlin/laravel-blade-snippets-vscode#6]
HTML autocomplete doesn't work in blade files. Is it possible to fix it? 
https://code.visualstudio.com/Docs/languages/html 

For example: `<a`  should give me `<a href="">`

**Comment by onecentlin** [comment]
@qcol Do you add below code to your user settings?

```
"emmet.syntaxProfiles": {
    "blade": "html"
},
```

**Comment by diazgilberto** [comment]
The setup above doesn't autocomplete either.
