### ISSUE TITLE
Strange syntax highlights

### ISSUE THREAD

**Issue by LC43** [onecentlin/laravel-blade-snippets-vscode#7]
Hi, thanks for your plugin!

i'm wondering tho, why this happens: ( the blue highlights )
![screenshot_2017-04-12_18-14-20](https://cloud.githubusercontent.com/assets/48201/24970507/7a07da9e-1fac-11e7-9082-2b5b88daacb9.png)

its the default Dark+ theme. ( and happens with most themes )

it has successfully detected is a blade template:

![screenshot_2017-04-12_18-14-20-laravel-blade](https://cloud.githubusercontent.com/assets/48201/24970517/847df1c0-1fac-11e7-96dd-5283f7117080.png)

code:
```

<style type="text/css">
    @php
    if( is_front_page() ) {
      $service_page_id = App\monfortur_get_option( 'monfortur_options_page_services' );
      $image_id = get_post_meta( $service_page_id, 'services_box_service_banner_id', true );
      $preloader = "";
      $image_large = "";
      $image_full = "";
      if( ! empty( $image_id ) ) {

        $preloader = wp_get_attachment_image_src( $image_id, 'preloader' );
        if( $preloader ){
          $preloader = base64_encode( file_get_contents( $preloader[0] ) );

        }
```

**Comment by onecentlin** [comment]
@LC43 Thanks for your feedback. I am still seeking a better solution to display syntax highlight in php section.

However, I personally prefer to reduce large block of php code in blade template. I would put those code into a service class and inject to blade. You may check [Service Injection](https://laravel.com/docs/5.4/blade#service-injection).

**Comment by LC43** [comment]
i'm seeing plain text in 1.8.1, which is less distracting than the blue highlights.

thanks,
closing.
