### ISSUE TITLE
nested templates are not highlighted

### ISSUE THREAD

**Issue by 7twin** [onecentlin/laravel-blade-snippets-vscode#70]
if you put for example an `@if` block inside a `@push` the `@if` will be white and not highlighted

**Comment by 7twin** [comment]
Just to update this issue a year later, it got even worse: having an if blade block inside a push, removes all syntax highlighting from the entire document forward.

**Comment by cpof-tea** [comment]
@7twin Could you, please, provide an example? My code shows no problem:
![image](https://user-images.githubusercontent.com/29537473/145881301-f83714b1-870b-4783-b5d8-2a38c46c0260.png)

**Comment by 7twin** [comment]
@cpof-tea it's been 3 years since the issue and it indeed seems fixed now, though I can't find the exact project I had the issue with, I quickly tested it and it was highlighted! closing unless someone else finds this issue reappearing. cheers. 🥂
