### ISSUE TITLE
Syntax highlighting broken following @php @endphp in HTML tag

### ISSUE THREAD

**Issue by dbhogg** [onecentlin/laravel-blade-snippets-vscode#79]
Using version 1.18.0 of Laravel Blade Snippets, version 1.27.2 of VS Code.

When using @php and @endphp directive inside an HTML tag, syntax highlighting for HTML breaks. 
![image](https://user-images.githubusercontent.com/7120579/45790496-fbe44900-bc39-11e8-9fd8-a6631b118985.png)

Additionally when using @php directive in quotations within an HTML tag provides similar result:
![image](https://user-images.githubusercontent.com/7120579/45790463-d48d7c00-bc39-11e8-8006-4f724fc6d483.png)

**Comment by cfaria** [comment]
Same problem here. VSCode 1.30.0. Laravel Blade Snippets version 1.18.0

**Comment by gitdward** [comment]
Same problem here VSCode v1.31.1 Laravel Blade Snippets v1.18.0

**Comment by brycefranzen** [comment]
Still an issue in VSCode v1.33.1 and Blade Snippets V1.20.0

**Comment by dotsam** [comment]
I have a possible fix in https://github.com/dotsam/laravel-blade-snippets-vscode/tree/php-section-fix but it might be heavy-handed and break other highlighting

**Comment by backtofront** [comment]
Still an issue VSCode 1.34.0 and Blade Snippets V1.20.0

**Comment by Kwaadpepper** [comment]
Is this project still maintained ? This is still an issue.

**Comment by onecentlin** [comment]
This issue is fixed in version 1.24.0
