### ISSUE TITLE
Hashtag throws off syntax highlighting

### ISSUE THREAD

**Issue by proevilz** [onecentlin/laravel-blade-snippets-vscode#80]
Within a Blade file, if you type a hashtag inside double curly braces, it almost acts as if it's a comment... is this intentional? How can I turn this off to just treat it like a normal hashtag?

`{{ # }}`

<img width="392" alt="screenshot 2018-09-30 at 19 08 46" src="https://user-images.githubusercontent.com/16267903/46260908-47bdaa80-c4e4-11e8-8c3e-1ec3080075a9.png">
<img width="381" alt="screenshot 2018-09-30 at 19 08 40" src="https://user-images.githubusercontent.com/16267903/46260909-47bdaa80-c4e4-11e8-8531-a67eb9b3ecfa.png">

**Comment by onecentlin** [comment]
Any reason for using `{{ # }}`?

**Comment by proevilz** [comment]
> Any reason for using `{{ # }}`?

Same reason as to why we use `{{ // }}` - it's valid PHP to create comments.
