### ISSUE TITLE
whenever i run formatter it adds new line before extends its annoying...

### ISSUE THREAD

**Issue by bhushangaykawad** [onecentlin/laravel-blade-snippets-vscode#89]
![Untitled](https://user-images.githubusercontent.com/43483545/57082866-7420eb80-6cac-11e9-9138-a2d393ff2d42.png)

everytime i run formatter it adds line below @extends or above @section..

**Comment by nimax1998** [comment]
same here !

**Comment by onecentlin** [comment]
Fixed in version 1.20.0, please update and try again, thanks!
