### ISSUE TITLE
Problems with Auto Indent

### ISSUE THREAD

**Issue by 1534286** [onecentlin/laravel-blade-snippets-vscode#9]
I noticed that there was another issue that covered the same topic but it was closed because it assumed the issue was related to VS Code due to PHP mode having the same problem. However, it looks like VS Code has fixed the problem with PHP mode and Auto Indent whereas this plugin still has the issue.

This is what happens in a normal HTML or PHP file:
```html
<html>(cursor here)</html>
```
When I press enter it'll give me:
```html
<html>
    (cursor here)
</html>
```
However, while in a Blade file I'll get this:
```html
<html>
(cursor here)</html>
```

The other issue that dealt with this is here: #2

**Comment by izcream** [comment]
i got this issue too

**Comment by izcream** [comment]
vscode latest version still not solve this problem

i attached GIF about this problem in this comment
![untitled](https://user-images.githubusercontent.com/10282500/29348271-9630da80-827c-11e7-8604-5b92f8a39165.gif)

**Comment by nicooprat** [comment]
I got the same behavior in html and blade files after adding this config:

```
"files.associations": {
    "*.blade.php": "html"
},
```

**Comment by 1534286** [comment]
I just tried that and it fixed the problem, but it would be nice if a work around wasn't required.

**Comment by nicooprat** [comment]
I just removed my comment, sorry. Original answer was to add this config:

```
"files.associations": {
   "*.blade.php": "html",
},
```

But I jsut found out that VScode will then open every new Blade file as a HTML file, which is not what we want. I first thought that the Blade syntax wasn't "inheriting' the HTML (or PHP) behavior and that this config would do the trick, but I'm not sure it's really the root of the issue...

**Comment by 1534286** [comment]
From something I read I got the impression that one of the latest pull requests had found a fix for this issue by adding the document format provider or something like that.

**Comment by andrade1379** [comment]
I'm seeing this problem as well

**Comment by ianmcqueen** [comment]
I am also seeing this problem. It seems that *.blade.php files aren't recognized as HTML files for auto indentation.

While putting this in my user settings files my auto indentation problem for Blade files:

    "files.associations": {
        "*.blade.php": "html"
    }

I then lose syntax highlighting for language constructs.

**Comment by nivv** [comment]
@ianmcqueen that's the same thing as uninstalling this package (almost)

**Comment by kuamatzin** [comment]
i got this issue too! =(

**Comment by aeschli** [comment]
To get auto indentation like html, the blade extension needs to do the same as here:
https://github.com/Microsoft/vscode/blob/72ea2ad8673b07d1432cff1f0ec52ca7ec37526c/extensions/html/client/src/htmlMain.ts#L119

**Comment by izcream** [comment]
i try to do like @aeschli comment but still not working or im do it wrong 😢 
i added this on `out/src/extenstion.js` in laravel-blade-snippet extensions folder

<img width="785" alt="screen shot 2017-11-09 at 11 08 54" src="https://user-images.githubusercontent.com/10282500/32588008-87a7b376-c53e-11e7-931e-cd9c8fc2efc6.png">

**Comment by aeschli** [comment]
Hm, that looks fine.

**Comment by izcream** [comment]
after edit that it's still not indent when i used emmet/blade
i dont know what i miss 😭

**Comment by ramya-rao-a** [comment]
@izcream Can you try something like this and see if that helps? https://github.com/Microsoft/vscode/pull/39523/commits/e13cc678d6092f77f5af918ebfbebce6e654dec4

**Comment by denizdogan** [comment]
Another example of when it fails horribly is this:

```
@extends('form.master')
@section('content')
```

becomes

```
@extends('form.master') @section('content')
```

**Comment by dpatou** [comment]
Is this considered fixed ? As pointed it's still not usabled in quite some cases.

Quick example, a blade file with
```
@extends('forms.master') 
@section('content') 
Oh Hi !
@endsection
```
formats to
```
@extends('forms.master') 
@section('content') Oh Hi !
@endsection
```
moreover, this (properly formatted by hand)
```
@extends('forms.master') 
@section('content')
    Lorem Ipsum
@endsection
@push('pagescripts')
<script>
    $(function(){
        console.log('Sit dolor');
    });
</script>
@endpush
@push('pagestyles')
<style>
    .someclass {
        color:#bada55;
    }
</style>
@endpush
```
formats to this
```
@extends('forms.master') 
@section('content') Lorem Ipsum
@endsection
 @push('pagescripts')
<script>
    $(function(){
        console.log('Sit dolor');
    });

</script>

@endpush @push('pagestyles')
<style>
    .someclass {
        color: #bada55;
    }
</style>

@endpush
```

Using vscode v 1.27.2
Using laravel blade snippets extension v 1.18.0

**Comment by neoighodaro** [comment]
Still having the same issue, as @dpatou. Any fix on the horizon?

**Comment by c0nst4ntin** [comment]
@onecentlin same issue still here! Any fixes or ideas?

```
@component('layouts.components.hero')
    <h1 class="display-4">
        @yield('hero-title')
    </h1>
    @hasSection ('hero-text')
        <p class="lead">
            @yield('hero-text')
        </p>
    @endif
@endcomponent

```
turns into:
```  
@component('layouts.components.hero')
<h1 class="display-4">
    @yield('hero-title')
</h1>
@hasSection ('hero-text')
<p class="lead">
    @yield('hero-text')
</p>
@endif
@endcomponent
```
Also:
```
@for ($monthKey = 1; $monthKey <= 12; $monthKey++) 
                        <option value="{{$monthKey}}" ....
```
turns into:
```
@for ($monthKey = 1; $monthKey <= 12; $monthKey++) <option value="{{$monthKey}}"
....
```
