### ISSUE TITLE
Infinite new line loop when saving .blade.php files that contain @ tags

### ISSUE THREAD

**Issue by gg3l** [onecentlin/laravel-blade-snippets-vscode#90]
Plugin version: 1.19.0

Description: Every time a .blade.php file that contains tags like **@extends**, **@section**, **@push**, etc. is saved, a new line is added before said tags.

Steps:
1. Go to Settings>Extensions and Enable Blade Format
2. Restart VSCode
3. Create a new *.blade.php file
4. Use tags like **@extends**, **@section**, **@push**, etc
5. Save document multiple times (CTRL+S)
6. Observe a new line is added, before @ tags, every time the document is being saved

Please see the [**video that details the issue**](https://click.email.vimeo.com/?qs=0bba097cc3b7db646a57233f72595339b4ce93ed802c3435a6e4b41bc6e8a2a70b13df6fe47faac8837d2d71bda64117abd4622671314974f69d39591f7dc5bb)

**Comment by tanshiqi** [comment]
same +1

**Comment by onecentlin** [comment]
Fixed in version 1.20.0, please update and try again, thanks!
