### ISSUE TITLE
Rename this

### ISSUE THREAD

**Issue by cjoftheweb** [onecentlin/laravel-blade-snippets-vscode#97]
This extension has both snippets and syntax highlighting, but the name implies it only has snippets. I'm willing to give you the laravel-blade-vscode name.

**Comment by Ares9323** [comment]
![image](https://user-images.githubusercontent.com/46932745/65135970-1c8ade80-da07-11e9-989f-4598cda46696.png)
It's written in the description

**Comment by mrleblanc101** [comment]
Except the description can be cut, and most people don't read it.
It should at least be the first element in the title.
Maybe something like `Laravel Blade Syntax & Snippets`
